// <auto-generated />
namespace DotNetCrud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class seeding_membershiptype_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seeding_membershiptype_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201811020036075_seeding_membershiptype_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
