// <auto-generated />
namespace DotNetCrud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_isactive_itemmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_isactive_itemmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201811012238457_added_isactive_itemmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
